(function(root){
  'use strict';
  const VERSION=2,days=['一','二','三','四','五','六','日'],dayMap=Object.fromEntries(days.map((d,i)=>[d,i+1]));dayMap.天=7;
  const periods=['08:00–08:45','08:50–09:35','10:00–10:45','10:50–11:35','11:40–12:25','13:25–14:10','14:15–15:00','15:05–15:50','16:15–17:00','17:05–17:50','18:50–19:35','19:40–20:25','20:30–21:15'];
  const uid=()=>root.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(36).slice(2),copy=x=>JSON.parse(JSON.stringify(x)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const makeTerms=()=>[['y1-fall','大一 · 秋冬'],['y1-spring','大一 · 春夏'],['y1-short','大一 · 短学期'],['y2-fall','大二 · 秋冬'],['y2-spring','大二 · 春夏'],['y2-short','大二 · 短学期'],['y3-fall','大三 · 秋冬'],['y3-spring','大三 · 春夏'],['y3-short','大三 · 短学期'],['y4-fall','大四 · 秋冬'],['y4-spring','大四 · 春夏']].map(([id,name],order)=>({id,name,order}));
  function empty(curriculum=null){return{kind:'zju-academic-plan',schemaVersion:VERSION,updatedAt:new Date().toISOString(),profile:{startYear:2025},terms:makeTerms(),selectedTerm:'y2-fall',curriculum:curriculum||{kind:'academic-curriculum-map',schemaVersion:1,metadata:{title:'尚未加载培养方案'},courses:[]},catalog:{courses:[],packages:[]},placements:[],activations:[]};}
  function normalizeState(raw,fallback){if(!raw||raw.kind!=='zju-academic-plan'||raw.schemaVersion!==VERSION)return empty(fallback?.curriculum||null);const s=copy(raw);s.terms=Array.isArray(s.terms)&&s.terms.length?s.terms:makeTerms();s.selectedTerm=s.terms.some(t=>t.id===s.selectedTerm)?s.selectedTerm:s.terms[0].id;s.catalog=s.catalog||{courses:[],packages:[]};s.catalog.courses=Array.isArray(s.catalog.courses)?s.catalog.courses:[];s.catalog.packages=Array.isArray(s.catalog.packages)?s.catalog.packages:[];s.placements=Array.isArray(s.placements)?s.placements:[];s.activations=Array.isArray(s.activations)?s.activations:[];return s;}
  const first=(o,keys)=>{for(const k of keys)if(o?.[k]!==undefined&&o[k]!==null&&String(o[k]).trim()!=='')return o[k];return''},num=x=>{const m=String(x??'').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):null};
  function parseTimes(text){const out=[],s=String(text||''),re=/周([一二三四五六日天])[^第\d]{0,12}第?\s*([\d\s,，\-—–至~]+)节/g;let m;while((m=re.exec(s))){const ps=[...m[2].matchAll(/\d{1,2}/g)].map(x=>+x[0]).filter(x=>x>=1&&x<=13);if(ps.length)out.push({day:dayMap[m[1]],start:Math.min(...ps),end:Math.max(...ps),raw:m[0]});}return out;}
  function courseFrom(o,source='导入课程包'){const code=String(first(o,['课程代码','课程号','kcdm','KCDM','code','courseCode'])).trim(),name=String(first(o,['课程名称','kcmc','KCMC','name','courseName'])).trim();if(!code&&!name)return null;const classId=String(first(o,['教学班','教学班号','jxb_id','jxbmc','classId','sectionId'])).trim(),time=String(first(o,['上课时间','sksj','time','schedule'])).trim(),place=String(first(o,['地点','上课地点','cdmc','place'])||'').trim(),times=parseTimes(time),dash=x=>!x||/^[-—－]+$/.test(x),shortTerm=Boolean(classId)&&dash(time)&&dash(place);return{id:code||name,code,name:name||code,credits:num(first(o,['学分','xf','XF','credits'])),weeklyHours:num(first(o,['周学时','weeklyHours'])),totalHours:num(first(o,['总学时','学时','zxs','hours','totalHours'])),source,offerings:classId||time?[{id:classId||uid(),teacher:String(first(o,['教师','jsxx','teacher'])||''),place,capacity:String(first(o,['容量','余量/容量','capacity'])||''),times,rawTime:time,shortTerm}]:[]};}
  function flatten(value,out=[]){if(Array.isArray(value))value.forEach(v=>flatten(v,out));else if(value&&typeof value==='object'){const c=courseFrom(value);if(c)out.push(value);Object.values(value).forEach(v=>{if(v&&typeof v==='object')flatten(v,out)});}return out;}
  function mergeCourses(list){const map=new Map();for(const c of list.filter(Boolean)){const key=(c.code||c.name).toUpperCase();if(!key)continue;let old=map.get(key);if(!old){old={...c,offerings:[...(c.offerings||[])]};map.set(key,old);continue;}for(const k of ['name','code','credits','weeklyHours','totalHours'])if((old[k]===null||old[k]==='')&&c[k]!==null&&c[k]!=='')old[k]=c[k];const seen=new Set(old.offerings.map(o=>o.id+'|'+o.rawTime));for(const o of c.offerings||[])if(!seen.has(o.id+'|'+o.rawTime)){old.offerings.push(o);seen.add(o.id+'|'+o.rawTime);}}for(const c of map.values()){c.offerings=(c.offerings||[]).filter(o=>(Array.isArray(o.times)&&o.times.length)||o.shortTerm);if(c.weeklyHours==null&&c.offerings.find(o=>o.times?.length))c.weeklyHours=c.offerings.find(o=>o.times?.length).times.reduce((n,t)=>n+t.end-t.start+1,0);}return[...map.values()];}
  function csvRows(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
  function objectsFromCsv(text){const rows=csvRows(text.replace(/^\uFEFF/,''));if(rows.length<2)return[];const head=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]??''])));}
  async function parsePackage(file,xlsxReader){if(/\.xlsx$/i.test(file.name)){if(!xlsxReader)throw Error('当前页面未加载 XLSX 读取器');const sheets=await xlsxReader(file),all=[];for(const sheet of sheets)for(const c of sheet.courses||[])all.push({id:c.code||c.name,code:c.code,name:c.name,credits:null,weeklyHours:null,totalHours:null,source:file.name+' · '+sheet.sheet,offerings:[{id:c.id||uid(),teacher:c.teacher||'',place:c.place||'',capacity:'',times:[{day:c.day,start:c.start,end:c.end}],rawTime:`周${days[c.day-1]} 第${c.start}–${c.end}节`}]});return mergeCourses(all);}const text=await file.text();if(/\.csv$/i.test(file.name))return mergeCourses(objectsFromCsv(text).map(o=>courseFrom(o,file.name)));const raw=JSON.parse(text),source=raw.page?.title||raw.exportedAt||file.name,objects=Array.isArray(raw.records)?raw.records.flatMap(r=>flatten(r.data??r)):flatten(raw);return mergeCourses(objects.map(o=>courseFrom(o,source)));}
  function validateCurriculum(c){if(!c||c.kind!=='academic-curriculum-map'||c.schemaVersion!==1||!Array.isArray(c.courses))throw Error('需要 academic-curriculum-map schemaVersion 1');for(const x of c.courses){if(!x.code&&!x.name)throw Error('存在缺少 code/name 的课程');if(!Array.isArray(x.recommendedTerms)||!Array.isArray(x.tags))throw Error(`${x.name||x.code} 缺少 recommendedTerms 或 tags`);}return c;}
  function download(name,text,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function mount(opts){
    const state=normalizeState(opts.initialState,opts.defaultState),host=opts.root,collapsedCourses=new Set(),expandedInactiveCourses=new Set();let search='',drag=null,warehouseCollapsed=false;
    const appearance=opts.standalone?'<div class="fp-appearance"><label>外观<select data-look><option value="studio">工作室</option><option value="linen">亚麻纸</option><option value="slate">石板蓝</option><option value="garden">花园</option></select></label><label>模式<select data-theme><option value="light">浅色</option><option value="dark">深色</option></select></label></div>':'';
    host.innerHTML=`<div class="fp-shell fp-week-mode"><header class="fp-top"><div class="fp-brand"><span class="fp-mark">∑</span><div><h1>课构 CourseCraft</h1><p>选择一个学期，把有时间的教学班拖进周课表</p></div></div><div class="fp-actions">${appearance}<button class="fp-btn" data-act="back">返回周视图</button><button class="fp-btn" data-act="export">导出规划</button><button class="fp-btn primary" data-act="activate">应用到 i-home</button></div></header><nav class="fp-term-tabs" aria-label="选择规划学期"></nav><div class="fp-planner-layout"><section class="fp-week-panel"><header class="fp-panel-title"><div><span class="fp-eyebrow">WEEKLY CANVAS</span><h2 data-term-title></h2></div><div data-term-stat></div></header><div class="fp-week-canvas"></div></section><aside class="fp-warehouse"><header><button class="fp-warehouse-toggle" data-act="warehouse" aria-expanded="true" title="收起课程仓库">⇥</button><div><span class="fp-eyebrow">COURSE WAREHOUSE</span><h2>课程仓库</h2></div><div class="fp-warehouse-actions"><button class="fp-btn" data-act="overview">课程总览</button><button class="fp-btn fp-package-button" data-act="package">导入课程包</button></div></header><div class="fp-search"><input data-search placeholder="搜索课程名、代码或教师"><span data-count></span></div><div class="fp-warehouse-list"></div><footer><button class="fp-btn" data-act="curriculum">导入培养方案映射</button><button class="fp-btn danger" data-act="clear-curriculum">删除培养方案映射</button><button class="fp-btn danger" data-act="clear">清空已导入课程</button></footer></aside></div><a class="fp-signature" href="https://deerflow.tech" target="_blank" rel="noreferrer">CREATED BY DEERFLOW</a><input data-file="package" type="file" accept=".json,.csv,.xlsx" hidden><input data-file="curriculum" type="file" accept=".json" hidden></div><dialog class="fp-dialog"></dialog>`;
    const $=s=>host.querySelector(s),all=s=>[...host.querySelectorAll(s)],dialog=$('.fp-dialog'),keyOf=c=>(c.code||c.name).toUpperCase();
    function combined(){const map=new Map((state.curriculum?.courses||[]).map(c=>[keyOf(c),{id:c.code||c.name,code:c.code||'',name:c.name||c.code,credits:c.credits??null,weeklyHours:null,totalHours:null,source:'培养方案',recommendedTerms:[...c.recommendedTerms],tags:[...c.tags],offerings:[]} ]));for(const c of state.catalog.courses){const key=keyOf(c),old=map.get(key);map.set(key,{...(old||{}),...c,recommendedTerms:old?.recommendedTerms||[],tags:old?.tags||[],offerings:c.offerings||[]});}return[...map.values()];}
    const findCourse=key=>combined().find(c=>keyOf(c)===String(key).toUpperCase()),findOffering=(c,id)=>c?.offerings?.find(o=>o.id===id),isActive=c=>(c.offerings||[]).some(o=>o.times?.length||o.shortTerm),courseTone=c=>(c.tags||[]).includes('必修')?'required':(c.tags||[]).includes('选修')?'elective':'ordinary',isShortTerm=()=>state.selectedTerm.endsWith('-short'),reduced=()=>root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
    function save(message){state.updatedAt=new Date().toISOString();opts.onSave?.(copy(state));render();if(message)opts.toast?.(message);}
    function animateIn(selector){if(reduced())return;all(selector).slice(0,18).forEach((node,index)=>node.animate([{opacity:0,transform:'translateY(8px) scale(.985)'},{opacity:1,transform:'none'}],{duration:260,delay:index*18,easing:'cubic-bezier(.22,.8,.2,1)',fill:'both'}));}
    function render(){renderTabs();renderWeek();renderWarehouse();animateIn('.fp-scheduled,.fp-short-card,.fp-warehouse-course');}
    function renderTabs(){$('.fp-term-tabs').innerHTML=state.terms.map(t=>`<button class="fp-term-tab" data-term="${t.id}" aria-current="${t.id===state.selectedTerm}">${esc(t.name)}</button>`).join('');all('[data-term]').forEach(b=>b.onclick=()=>{state.selectedTerm=b.dataset.term;save();});}
    function laneFor(blocks,index){let lane=0;while(blocks.slice(0,index).some(b=>b.day===blocks[index].day&&b.start<=blocks[index].end&&b.end>=blocks[index].start&&b.lane===lane))lane++;return lane;}
    function renderWeek(){
      const term=state.terms.find(t=>t.id===state.selectedTerm),placements=state.placements.filter(p=>p.termId===state.selectedTerm),blocks=[];
      $('[data-term-title]').textContent=term?.name||state.selectedTerm;
      const credits=[...new Set(placements.map(p=>p.courseKey))].reduce((n,k)=>n+(findCourse(k)?.credits||0),0);
      $('[data-term-stat]').innerHTML=`<strong>${placements.length}</strong> 个教学班 · <strong>${credits.toFixed(1)}</strong> 学分`;
      if(isShortTerm()){
        const cards=placements.map(p=>{const c=findCourse(p.courseKey),o=findOffering(c,p.offeringId);if(!c||!o)return'';return`<article class="fp-short-card ${courseTone(c)}" data-remove="${p.id}"><button aria-label="移除">×</button><div><strong>${esc(c.name)}</strong><span>${esc(c.code)} · ${c.credits??'?'} 学分</span></div><p>${esc(o.teacher||'教师待定')} · 集中实践课程 · 时间地点另行通知</p></article>`}).join('');
        $('.fp-week-canvas').className='fp-week-canvas fp-short-canvas';$('.fp-week-canvas').innerHTML=`<div class="fp-short-drop"><span>SHORT TERM</span><h3>短学期课程清单</h3><p>把时间与地点均为“--”的教学班拖到这里。短学期不占用周历节次。</p></div><div class="fp-short-list">${cards||'<div class="fp-empty">尚未安排短学期课程</div>'}</div>`;bindShortDrop();
      }else{
        for(const p of placements){const c=findCourse(p.courseKey),o=findOffering(c,p.offeringId);for(const t of o?.times||[])blocks.push({p,c,o,...t,lane:0,lanes:1});}
        blocks.sort((a,b)=>a.day-b.day||a.start-b.start);blocks.forEach((b,i)=>b.lane=laneFor(blocks,i));for(const b of blocks)b.lanes=Math.max(1,...blocks.filter(x=>x.day===b.day&&x.start<=b.end&&x.end>=b.start).map(x=>x.lane+1));
        let html='<div class="fp-grid-corner">节次 / 时间</div>'+days.map(d=>`<div class="fp-grid-day">周${d}</div>`).join('');for(let p=1;p<=13;p++){html+=`<div class="fp-grid-time"><b>${p}</b><span>${periods[p-1]}</span></div>`;for(let d=1;d<=7;d++)html+=`<div class="fp-grid-cell" data-day="${d}" data-period="${p}" style="grid-column:${d+1};grid-row:${p+1}"></div>`;}html+=blocks.map(b=>`<article class="fp-scheduled ${courseTone(b.c)}" style="grid-column:${b.day+1};grid-row:${b.start+1}/span ${b.end-b.start+1};--lane:${b.lane};--lanes:${b.lanes}" data-remove="${b.p.id}" title="${esc(b.c.name)} · ${esc(b.o.teacher)} · ${esc(b.o.place)}"><button aria-label="移除">×</button><strong>${esc(b.c.name)}</strong><span>${esc(b.o.place||'地点待定')}</span><small>${b.start}–${b.end}节</small></article>`).join('');$('.fp-week-canvas').className='fp-week-canvas';$('.fp-week-canvas').innerHTML=html;bindCells();
      }
      all('[data-remove]').forEach(b=>b.onclick=()=>{state.placements=state.placements.filter(p=>p.id!==b.dataset.remove);save('已从本学期课表移除')});
    }
    function offeringLabel(o){return o.shortTerm?'短学期集中课程':(o.rawTime||o.times.map(t=>`周${days[t.day-1]} ${t.start}–${t.end}节`).join('；'));}
    function renderWarehouse(){
      let list=combined().filter(c=>!search||`${c.name} ${c.code} ${(c.offerings||[]).map(o=>o.teacher).join(' ')}`.toLowerCase().includes(search));
      list.sort((a,b)=>Number(!(a.recommendedTerms||[]).includes(state.selectedTerm))-Number(!(b.recommendedTerms||[]).includes(state.selectedTerm))||Number(!isActive(a))-Number(!isActive(b))||a.name.localeCompare(b.name,'zh-CN'));
      $('[data-count]').textContent=`${list.length} 门 · ${list.filter(isActive).length} 门已激活`;
      $('.fp-warehouse-list').innerHTML=list.map(c=>{const key=c.code||c.name,recommended=(c.recommendedTerms||[]).includes(state.selectedTerm),active=isActive(c),open=active?!collapsedCourses.has(keyOf(c)):expandedInactiveCourses.has(keyOf(c)),tone=courseTone(c),tags=(c.tags||[]).map(t=>`<span class="fp-course-tag ${tone}">${esc(t)}</span>`).join(''),offerings=active?(c.offerings||[]).map(o=>{const compatible=isShortTerm()?o.shortTerm:!o.shortTerm&&o.times?.length;return`<button type="button" class="fp-offering${compatible?'':' incompatible'}" data-course="${esc(key)}" data-offering="${esc(o.id)}"><span>${esc(o.teacher||'教师待定')}</span><small>${esc(offeringLabel(o))}${o.place&&!o.shortTerm?` · ${esc(o.place)}`:''}</small></button>`}).join(''):'<p class="fp-inactive-hint">待导入含有效时间的课程信息</p>';return`<article class="fp-warehouse-course ${tone}${active?'':' inactive'}${recommended?' recommended':''}${open?' expanded':''}"><button class="fp-course-summary" data-expand="${esc(key)}" aria-expanded="${open}"><span class="fp-chevron">⌄</span><span><strong>${esc(c.name)}</strong><small>${esc(c.code)}${c.credits!=null?` · ${c.credits} 学分`:''}</small></span><span class="fp-status">${active?(c.offerings.some(o=>o.shortTerm)?'短学期':'已激活'):'未激活'}</span></button>${open?`<div class="fp-tags">${recommended?'<span class="fp-course-tag recommended">本学期推荐</span>':''}${tags}</div><div class="fp-course-details">${offerings}<button class="fp-edit-course" data-edit="${esc(key)}">编辑课程信息</button></div>`:`${recommended?'<div class="fp-tags"><span class="fp-course-tag recommended">本学期推荐</span></div>':''}`}</article>`}).join('')||'<div class="fp-empty">没有匹配课程</div>';
      all('[data-expand]').forEach(b=>b.onclick=()=>{const k=b.dataset.expand.toUpperCase(),c=findCourse(k),set=isActive(c)?collapsedCourses:expandedInactiveCourses;if(isActive(c)){set.has(k)?set.delete(k):set.add(k)}else{set.has(k)?set.delete(k):set.add(k)}renderWarehouse();animateIn('.fp-warehouse-course.expanded .fp-course-details')});
      all('[data-edit]').forEach(b=>b.onclick=()=>editCourse(b.dataset.edit));
      all('.fp-offering:not(.incompatible)').forEach(bindOffering);
    }
    function dropTargetAt(x,y){const node=root.document.elementFromPoint(x,y);return node?.closest?.('.fp-grid-cell,.fp-short-drop')||null;}
    function acceptsDrop(target,courseKey,offeringId){const o=findOffering(findCourse(courseKey),offeringId);if(!target||!o)return false;if(target.matches('.fp-short-drop'))return isShortTerm()&&o.shortTerm;if(isShortTerm()||!target.matches('.fp-grid-cell'))return false;return o.times?.some(t=>t.day===Number(target.dataset.day)&&t.start===Number(target.dataset.period));}
    function clearCourseDrag(){drag=null;host.classList.remove('is-course-dragging');root.document.querySelectorAll('.fp-drag-ghost').forEach(n=>n.remove());all('.fp-grid-cell,.fp-short-drop').forEach(n=>n.classList.remove('valid-drop','invalid-drop','is-over'));all('.fp-offering').forEach(n=>n.classList.remove('dragging','selected'));}
    function placeOffering(courseKey,offeringId){if(!findOffering(findCourse(courseKey),offeringId))return;const exists=state.placements.some(p=>p.termId===state.selectedTerm&&p.courseKey===courseKey&&p.offeringId===offeringId);if(!exists)state.placements.push({id:uid(),termId:state.selectedTerm,courseKey,offeringId});clearCourseDrag();save(exists?'该教学班已在课表中':isShortTerm()?'短学期课程已加入':'教学班已加入课表');}
    function bindOffering(button){
      button.onclick=()=>{if(button.dataset.justDragged){delete button.dataset.justDragged;return;}const next={courseKey:button.dataset.course,offeringId:button.dataset.offering};if(drag?.courseKey===next.courseKey&&drag?.offeringId===next.offeringId){clearCourseDrag();opts.toast?.('已取消选择');return;}clearCourseDrag();drag=next;button.classList.add('selected');host.classList.add('is-course-dragging');highlightDrops();opts.toast?.(isShortTerm()?'已选择教学班，请点击短学期清单':'已选择教学班，请点击高亮的起始节次');};
      button.onpointerdown=e=>{if(e.button!==0)return;const startX=e.clientX,startY=e.clientY,info={courseKey:button.dataset.course,offeringId:button.dataset.offering};let moved=false,ghost=null;
        const move=ev=>{if(!moved&&Math.hypot(ev.clientX-startX,ev.clientY-startY)<5)return;if(!moved){moved=true;clearCourseDrag();drag=info;host.classList.add('is-course-dragging');button.classList.add('dragging');ghost=button.cloneNode(true);ghost.classList.add('fp-drag-ghost');ghost.removeAttribute('data-course');ghost.removeAttribute('data-offering');root.document.body.append(ghost);highlightDrops();}ev.preventDefault();ghost.style.left=`${ev.clientX+14}px`;ghost.style.top=`${ev.clientY+14}px`;all('.fp-grid-cell,.fp-short-drop').forEach(n=>n.classList.remove('is-over'));const target=dropTargetAt(ev.clientX,ev.clientY);if(acceptsDrop(target,info.courseKey,info.offeringId))target.classList.add('is-over');};
        const up=ev=>{root.document.removeEventListener('pointermove',move,true);root.document.removeEventListener('pointerup',up,true);if(!moved)return;button.dataset.justDragged='1';setTimeout(()=>delete button.dataset.justDragged,0);const target=dropTargetAt(ev.clientX,ev.clientY);if(acceptsDrop(target,info.courseKey,info.offeringId))placeOffering(info.courseKey,info.offeringId);else{clearCourseDrag();opts.toast?.('请放到高亮的课程起始节次')}};
        root.document.addEventListener('pointermove',move,true);root.document.addEventListener('pointerup',up,true);
      };
    }
    function showOverview(){const courses=combined().sort((a,b)=>Number(!isActive(a))-Number(!isActive(b))||a.name.localeCompare(b.name,'zh-CN')),active=courses.filter(isActive).length,offerings=courses.reduce((n,c)=>n+(c.offerings||[]).length,0);dialog.classList.add('fp-overview-dialog');dialog.addEventListener('close',()=>dialog.classList.remove('fp-overview-dialog'),{once:true});dialog.innerHTML=`<h2>全部课程仓库</h2><p>${courses.length} 门课程 · ${active} 门已激活 · ${offerings} 个教学班。这里同时列出课程包中的有效课程与培养方案中的灰色待激活课程。</p><div class="fp-overview-table"><div class="fp-overview-head"><span>课程</span><span>状态</span><span>标签</span><span>推荐学期</span><span>教学班</span><span></span></div>${courses.map(c=>`<div class="fp-overview-row${isActive(c)?'':' inactive'}"><span><strong>${esc(c.name)}</strong><small>${esc(c.code)}${c.credits!=null?` · ${c.credits} 学分`:''}</small></span><span>${isActive(c)?'已激活':'待激活'}</span><span>${esc((c.tags||[]).join('、')||'普通')}</span><span>${esc((c.recommendedTerms||[]).map(id=>state.terms.find(t=>t.id===id)?.name||id).join('、')||'—')}</span><span>${(c.offerings||[]).length}</span><button class="fp-edit-course" data-overview-edit="${esc(c.code||c.name)}">编辑</button></div>`).join('')}</div><div class="fp-dialog-actions"><button class="fp-btn primary" data-close-overview>关闭</button></div>`;dialog.querySelector('[data-close-overview]').onclick=()=>dialog.close();dialog.querySelectorAll('[data-overview-edit]').forEach(b=>b.onclick=()=>{dialog.close();editCourse(b.dataset.overviewEdit)});dialog.showModal();}
    function editCourse(key){const c=findCourse(key);if(!c)return;const offerings=(c.offerings||[]);dialog.innerHTML=`<h2>编辑课程信息</h2><p>课程代码作为培养方案和课程包的匹配键，不在这里修改。</p><label>课程代码<input data-code value="${esc(c.code)}" readonly></label><label>课程名称<input data-name value="${esc(c.name)}"></label><label>学分<input data-credit type="number" min="0" step="0.5" value="${c.credits??''}"></label><label>标签（逗号分隔）<input data-tags value="${esc((c.tags||[]).join(','))}"></label><label>推荐学期（逗号分隔）<input data-terms value="${esc((c.recommendedTerms||[]).join(','))}"></label><div class="fp-offering-editor">${offerings.map((o,i)=>`<fieldset><legend>教学班 ${i+1}${o.shortTerm?' · 短学期':''}</legend><label>教师<input data-teacher="${i}" value="${esc(o.teacher)}"></label><label>上课时间<input data-time="${i}" value="${esc(o.rawTime)}" placeholder="周四第3,4,5节 或 --"></label><label>地点<input data-place="${i}" value="${esc(o.place)}"></label></fieldset>`).join('')||'<p class="fp-warning">当前只有培养方案提示，导入课程包后才会出现教学班。</p>'}</div><div class="fp-dialog-actions"><button class="fp-btn" data-cancel>取消</button><button class="fp-btn primary" data-ok>保存修改</button></div>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-ok]').onclick=()=>{const name=dialog.querySelector('[data-name]').value.trim(),credits=num(dialog.querySelector('[data-credit]').value),tags=dialog.querySelector('[data-tags]').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),recommendedTerms=dialog.querySelector('[data-terms]').value.split(/[,，]/).map(x=>x.trim()).filter(x=>state.terms.some(t=>t.id===x));let mapItem=(state.curriculum.courses||[]).find(x=>keyOf(x)===keyOf(c));if(!mapItem){mapItem={code:c.code,name,credits,recommendedTerms,tags};state.curriculum.courses.push(mapItem)}else Object.assign(mapItem,{name,credits,recommendedTerms,tags});const imported=state.catalog.courses.find(x=>keyOf(x)===keyOf(c));if(imported){imported.name=name;imported.credits=credits;offerings.forEach((o,i)=>{o.teacher=dialog.querySelector(`[data-teacher="${i}"]`).value.trim();o.rawTime=dialog.querySelector(`[data-time="${i}"]`).value.trim();o.place=dialog.querySelector(`[data-place="${i}"]`).value.trim();o.times=parseTimes(o.rawTime);o.shortTerm=/^[-—－]+$/.test(o.rawTime)&&(!o.place||/^[-—－]+$/.test(o.place));});}dialog.close();save('课程信息已更新')};dialog.showModal();}
    function bindShortDrop(){const zone=$('.fp-short-drop');if(!zone)return;zone.onclick=()=>{if(drag&&acceptsDrop(zone,drag.courseKey,drag.offeringId))placeOffering(drag.courseKey,drag.offeringId)};}
    function highlightDrops(){if(isShortTerm()){$('.fp-short-drop')?.classList.toggle('valid-drop',!!findOffering(findCourse(drag?.courseKey),drag?.offeringId)?.shortTerm);return;}all('.fp-grid-cell').forEach(cell=>{const c=findCourse(drag?.courseKey),o=findOffering(c,drag?.offeringId),valid=o?.times?.some(t=>t.day===+cell.dataset.day&&t.start===+cell.dataset.period);cell.classList.toggle('valid-drop',!!valid);cell.classList.toggle('invalid-drop',!valid);});}
    function bindCells(){all('.fp-grid-cell').forEach(cell=>{cell.onclick=()=>{if(drag&&acceptsDrop(cell,drag.courseKey,drag.offeringId))placeOffering(drag.courseKey,drag.offeringId)};});}
    function reviewImport(file,courses){let keep=new Set(courses.filter(isActive).map(keyOf));function draw(){dialog.innerHTML=`<h2>审视本次课程包</h2><p>共识别 ${courses.length} 门课程。有星期/节次，或时间与地点均为“--”的短学期教学班可导入；可以逐门叉掉或批量选择。</p><div class="fp-review-actions"><button class="fp-btn" data-all>全选可用课程</button><button class="fp-btn" data-none>全部清空</button><span>将导入 ${keep.size} 门</span></div><div class="fp-import-review">${courses.map(c=>{const short=c.offerings.filter(o=>o.shortTerm).length,timed=c.offerings.filter(o=>o.times?.length).length;return`<article class="fp-review-row${keep.has(keyOf(c))?'':' removed'}"><label><input type="checkbox" data-keep="${esc(keyOf(c))}" ${keep.has(keyOf(c))?'checked':''} ${isActive(c)?'':'disabled'}><span><strong>${esc(c.name)}</strong><small>${esc(c.code)} · ${c.credits??'?'} 学分 · ${timed} 个周课教学班${short?` · ${short} 个短学期教学班`:''}</small></span></label><button data-x="${esc(keyOf(c))}" aria-label="排除">×</button></article>`}).join('')}</div><div class="fp-dialog-actions"><button class="fp-btn" data-cancel>取消</button><button class="fp-btn primary" data-ok>导入保留课程</button></div>`;dialog.querySelector('[data-all]').onclick=()=>{keep=new Set(courses.filter(isActive).map(keyOf));draw()};dialog.querySelector('[data-none]').onclick=()=>{keep.clear();draw()};dialog.querySelectorAll('[data-keep]').forEach(x=>x.onchange=()=>{x.checked?keep.add(x.dataset.keep):keep.delete(x.dataset.keep);draw()});dialog.querySelectorAll('[data-x]').forEach(x=>x.onclick=()=>{keep.delete(x.dataset.x);draw()});dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-ok]').onclick=()=>{const accepted=courses.filter(c=>keep.has(keyOf(c)));state.catalog.courses=mergeCourses([...state.catalog.courses,...accepted]);state.catalog.packages.push({name:file.name,importedAt:new Date().toISOString(),recognized:courses.length,accepted:accepted.length});dialog.close();save(`已导入 ${accepted.length} 门可用课程`)};}draw();dialog.showModal();}
    function clearCatalog(){dialog.innerHTML='<h2>清空已导入课程？</h2><p>这会删除全部已激活课程、教学班和本学期排课。培养方案映射会保留为灰色提示。</p><div class="fp-dialog-actions"><button class="fp-btn" data-cancel>取消</button><button class="fp-btn danger" data-ok>确认清空</button></div>';dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-ok]').onclick=()=>{state.catalog={courses:[],packages:[]};state.placements=[];dialog.close();save('已清空课程库和排课')};dialog.showModal();}
    function clearCurriculum(){const count=state.curriculum?.courses?.length||0;if(!count){opts.toast?.('当前没有培养方案映射');return;}dialog.innerHTML=`<h2>删除培养方案映射？</h2><p>将删除 ${count} 条课程与建议学期的对应关系。已经导入的课程包、教学班和排课不会被删除。</p><div class="fp-dialog-actions"><button class="fp-btn" data-cancel>取消</button><button class="fp-btn danger" data-ok>确认删除</button></div>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-ok]').onclick=()=>{state.curriculum={kind:'academic-curriculum-map',schemaVersion:1,metadata:{title:'尚未加载培养方案'},courses:[]};expandedInactiveCourses.clear();dialog.close();save('已删除培养方案映射')};dialog.showModal();}
    function activate(){const ps=state.placements.filter(p=>p.termId===state.selectedTerm),selected=ps.map(p=>{const course=findCourse(p.courseKey),offering=findOffering(course,p.offeringId);return{placement:p,course,offering}}).filter(x=>x.course&&x.offering);dialog.innerHTML=`<h2>应用当前学期到 i-home</h2><p>将写入 ${selected.length} 个教学班。重叠课程会原样保留。</p><label>生效日期<input data-from type="date"></label><label>结束日期<input data-to type="date"></label><div class="fp-dialog-actions"><button class="fp-btn" data-cancel>取消</button><button class="fp-btn primary" data-ok>应用</button></div>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-ok]').onclick=()=>{const from=dialog.querySelector('[data-from]').value,to=dialog.querySelector('[data-to]').value;if(!from||!to||from>to){opts.toast?.('请填写有效起止日期');return;}opts.onActivate?.({termId:state.selectedTerm,from,to,selected});state.activations.push({id:uid(),termId:state.selectedTerm,from,to,createdAt:new Date().toISOString()});dialog.close();save('当前学期已应用到 i-home')};dialog.showModal();}
    $('[data-search]').oninput=e=>{search=e.target.value.trim().toLowerCase();renderWarehouse()};$('[data-act="back"]').onclick=()=>opts.onBack?.();$('[data-act="export"]').onclick=()=>download(`future-plan-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2));$('[data-act="activate"]').onclick=activate;$('[data-act="clear"]').onclick=clearCatalog;$('[data-act="clear-curriculum"]').onclick=clearCurriculum;$('[data-act="package"]').onclick=()=>$('[data-file="package"]').click();$('[data-act="curriculum"]').onclick=()=>$('[data-file="curriculum"]').click();$('[data-act="overview"]').onclick=showOverview;$('[data-act="warehouse"]').onclick=()=>{warehouseCollapsed=!warehouseCollapsed;$('.fp-planner-layout').classList.toggle('warehouse-collapsed',warehouseCollapsed);$('.fp-warehouse').classList.toggle('collapsed',warehouseCollapsed);const b=$('[data-act="warehouse"]');b.setAttribute('aria-expanded',String(!warehouseCollapsed));b.title=warehouseCollapsed?'展开课程仓库':'收起课程仓库';b.textContent=warehouseCollapsed?'⇤':'⇥'};
    if(opts.standalone){let savedAppearance={};try{savedAppearance=JSON.parse(localStorage.getItem('future-planner.appearance')||'{}')}catch{}const look=$('[data-look]'),theme=$('[data-theme]');look.value=savedAppearance.look||document.documentElement.dataset.look||'studio';theme.value=savedAppearance.theme||document.documentElement.dataset.theme||'light';const applyAppearance=()=>{document.documentElement.dataset.look=look.value;document.documentElement.dataset.theme=theme.value;localStorage.setItem('future-planner.appearance',JSON.stringify({look:look.value,theme:theme.value}))};look.onchange=theme.onchange=applyAppearance;applyAppearance();}
    $('[data-file="package"]').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{reviewImport(file,await parsePackage(file,opts.xlsxReader))}catch(err){opts.toast?.('课程包未读取：'+err.message)}};$('[data-file="curriculum"]').onchange=e=>{const file=e.target.files[0];e.target.value='';if(!file)return;file.text().then(text=>{try{state.curriculum=validateCurriculum(JSON.parse(text));save(`已加载 ${state.curriculum.courses.length} 条培养方案映射`)}catch(err){opts.toast?.('培养方案未导入：'+err.message)}})};
    render();return{state,render};
  }
  root.FuturePlanner={mount,empty,normalizeState,parsePackage,validateCurriculum,mergeCourses,parseTimes};
})(typeof window!=='undefined'?window:globalThis);

